apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd-fusion-v1.0
  namespace: kube-system
  labels:
    k8s-app: fluentd-fusion
    kubernetes.io/cluster-service: "true"
    version: v1.00
spec:
  serviceAccountName: tiller
  template:
    metadata:
      labels:
        k8s-app: fluentd-fusion
        kubernetes.io/cluster-service: "true"
        version: v1.0
    spec:
      containers:
        - name: fluentd-fusion
          imagePullPolicy: IfNotPresent
          image: lucidworks/fluentd-fusion:20170908121509
          command:
            - '/bin/sh'
            - '-c'
            - '/usr/sbin/td-agent 2>&1 >> /var/log/fluentd.log'
          env:
            - name: FUSION_USERNAME
              value: "admin"
            - name: FUSION_PASSWORD
              value: "password123"
            - name: FUSION_LOG_COLLECTION
              value: "default"
            - name: FUSION_HOST
              value: "10.101.100.110"
              #valueFrom:
              #  fieldRef:
              #    fieldPath: status.podIP # For local testing, have fusion log to itself.
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: varlibdockersymlinks
              mountPath: /mnt/sda1/var/lib/docker/containers/
              readOnly: true
            - name: apilog
              mountPath: /opt/fusion/var/log/api
            - name: connectorslog
              mountPath: /opt/fusion/var/log/connectors
            - name: solrlog
              mountPath: /opt/fusion/var/log/solr
            - name: zklog
              mountPath: /opt/fusion/var/log/zookeeper
            - name: uilog
              mountPath: /opt/fusion/var/log/ui
        #- name: fusion
        #  imagePullPolicy: IfNotPresent
        #  image: lucidworks/fusion:latest
        #  ports:
        #    - containerPort: 8764
        #      hostPort: 8764
        #  env:
        #    - name: SET_ADMIN_CREDENTIALS
        #      value: "1"
        #    - name: group_default
        #      value: "zookeeper, solr, api, connectors, ui"
        #  volumeMounts:
        #    - name: apilog
        #      mountPath: /opt/fusion/var/log/api
        #    - name: connectorslog
        #      mountPath: /opt/fusion/var/log/connectors
        #    - name: solrlog
        #      mountPath: /opt/fusion/var/log/solr
        #    - name: zklog
        #      mountPath: /opt/fusion/var/log/zookeeper
        #    - name: uilog
        #      mountPath: /opt/fusion/var/log/ui
      terminationGracePeriodSeconds: 0
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker
        - name: varlibdockersymlinks
          hostPath:
              path: /mnt/sda1/var/lib/docker/containers/
        - name: apilog
          emptyDir: {}
        - name: connectorslog
          emptyDir: {}
        - name: solrlog
          emptyDir: {}
        - name: zklog
          emptyDir: {}
        - name: uilog
          emptyDir: {}