apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd-fusion-v1.0
  namespace: kube-system
  labels:
    k8s-app: fluentd-fusion
    kubernetes.io/cluster-service: "true"
    version: v1.00
spec:
  template:
    metadata:
      labels:
        k8s-app: fluentd-fusion
        kubernetes.io/cluster-service: "true"
        version: v1.0
    spec:
    #  kubectl create secret docker-registry lucidworks-dockerhub --docker-server=https://registry.hub.docker.com/v1/ --docker-username="$HUB_USERNAME" --docker-password="$HUB_PASSWORD" --docker-email="john.gibson@lucidworks.com"
      imagePullSecrets:
        - name: lucidworks-dockerhub
      containers:
        #- name: fluentd-fusion
        #  imagePullPolicy: Never # TODO: Remove
        #  image: fluentdtest #lucidworks/kubernetes-fluentd-fusion:1.0
        #  command:
        #    - '/bin/sh'
        #    - '-c'
        #    - '/usr/sbin/td-agent 2>&1 >> /var/log/fluentd.log'
        #  env:
        #    - name: FUSION_USERNAME
        #      value: "admin"
        #    - name: FUSION_PASSWORD
        #      value: "password123"
        #    - name: FUSION_HOST
        #      value: "192.168.1.15" #TODO: change
        #  resources:
        #    limits:
        #      memory: 200Mi
        #    requests:
        #      cpu: 100m
        #      memory: 200Mi
        #  volumeMounts:
        #    - name: varlog
        #      mountPath: /var/log
        #    - name: varlibdockercontainers
        #      mountPath: /var/lib/docker/containers
        #      readOnly: true
        #    - name: apilog
        #      mountPath: /opt/fusion/var/log/api
        #    - name: connectorslog
        #      mountPath: /opt/fusion/var/log/connectors
        #    - name: solrlog
        #      mountPath: /opt/fusion/var/log/solr
        #    - name: zklog
        #      mountPath: /opt/fusion/var/log/zookeeper
        #    - name: uilog
        #      mountPath: /opt/fusion/var/log/ui
        - name: fusion
          imagePullPolicy: Never # TODO: Remove
          image: lucidworks/fusion:appkit3
          ports:
            - containerPort: 8764
              hostPort: 8764
          volumeMounts:
            - name: apilog
              mountPath: /opt/fusion/var/log/api
            - name: connectorslog
              mountPath: /opt/fusion/var/log/connectors
            - name: solrlog
              mountPath: /opt/fusion/var/log/solr
            - name: zklog
              mountPath: /opt/fusion/var/log/zookeeper
            - name: uilog
              mountPath: /opt/fusion/var/log/ui


      # nodeSelector:
      #   alpha.kubernetes.io/fluentd-ds-ready: "true"
      terminationGracePeriodSeconds: 0

      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: apilog
          emptyDir: {}
        - name: connectorslog
          emptyDir: {}
        - name: solrlog
          emptyDir: {}
        - name: zklog
          emptyDir: {}
        - name: uilog
          emptyDir: {}